### DISCUSSION TITLE
Perfect Local Theme Development Setup

### DISCUSSION THREAD

**Discussion by saschaseniuk** [tailpress/tailpress#24] [Q&A]
I was wondering how a perfect setup for local development could look like.

What is the best practice to spin up a local WordPress installation and how to "link" my newly created Node dev environment with the WordPress themes folder?

**Comment by ethan-tqa** [comment]
So far I have found LocalWP to be the least painful way to quickly spin up dev env

**Comment by jeffreyvr** [comment]
I've been using [Laravel Valet](https://laravel.com/docs/8.x/valet) for all my local development (WordPress + Laravel). I really like it.

Then I have a bash script with which I can quickly spin up a new WordPress site that pre-installs a fresh copy of TailPress and my debugging plugin.

**Reply by ethan-tqa** [reply]
Looks like it only works on Mac?

**Reply by jeffreyvr** [reply]
Correct, Valet only works on Mac.

**Reply by striberny** [reply]
For Windows I can recommend Laragon.

**Comment by dapunkt** [comment]
I am using Local with VS code (or sometimes Panic Nova) in combination with managed WordPress hosting from Getflywheel (freelance package), not cheap but very productive, especially when you use TailPress ;)

**Comment by tim-the-arcane** [comment]
For basic theme development I normally use a basic [Docker Compose script straight from the Docker Documentation](https://docs.docker.com/samples/wordpress/) with a few adjustments for my M1 Mac (no MySQL-Support yet but MariaDB works fine.):

```yaml
# docker-compose.yml
version: "3.9"

services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/themes/tailpress:cached
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
  wordpress_data: {}
```
Drop this in the theme project folder and run `docker compose up -d`.

When I'm done with my work I just delete the container. Can't get any cleaner than that IMHO! :) 

I just found this theme. Very nice and super useful. Will definitely check it out in my next private WordPress project!

**Reply by jeffreyvr** [reply]
Thanks for sharing @tim-the-arcane! Used docker for a Laravel application recently (through Laravel Sail), so interesting to see how I might use this for WP projects too. Do you know what PHP version comes with this container?

**Reply by tim-the-arcane** [reply]
I'm happy to share if it helps you and others in the community.

By default it seems to be using PHP 7.4. You can specify which PHP version you want though by appending it as a tag to the image name in the docker-compose.yml.

E.g. for PHP 8.1:

```yaml
# [...]
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1
# [...]
``` 

You can see all available tags here: https://hub.docker.com/_/wordpress (It's a bit messy though imo)
